### ISSUE TITLE
downloaded_Donald_Trump.txt

### ISSUE THREAD

**Issue by andreasvlachos** [sheffieldnlp/stance-conditional#12]
When I run it, I get this:
```
python word2vec_training.py 
Traceback (most recent call last):
  File "word2vec_training.py", line 67, in <module>
    tweets_trump, targets_trump, labels_trump, ids_trump = reader.readTweetsOfficial("../data/downloaded_Donald_Trump.txt", "utf-8", 1)
  File "/Users/andreasvlachos/Work/git/stance-conditional/readwrite/reader.py", line 17, in readTweetsOfficial
    for line in io.open(tweetfile, encoding=encoding, mode='r'):
FileNotFoundError: [Errno 2] No such file or directory: '../data/downloaded_Donald_Trump.txt'
```
Is `downloaded_Donald_Trump.txt` the same file as `downloaded_Donald_Trump_all.txt` (which is in the dropbox folder)?

**Comment by isabelleaugenstein** [comment]
Yes, sorry. I changed the filename in the Dropbox folder now to make it clear.
There were also some other filename inconsistencies in the code which should now be fixed.
